steps:
 - name: 'gcr.io/cloud-builders/docker'
   id: Build-Deployer
   args:
   - 'build'
   - '-t'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory/deployer:7.19'
   - '.' 

 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args: 
     - "-c"
     - |
         cd jfrog-artifactory
         ls 
 - name: 'gcr.io/cloud-builders/docker'
   id: BuildRT
   args:
   - 'build'
   - '-t'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory:7.19.4'
   - '-f'
   - 'jfrog-artifactory/Dockerfile.artifactory'
   - '.' 

 - name: 'gcr.io/cloud-builders/docker'
   id: BuildNG
   args:
   - 'build'
   - '-t'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory/nginx-artifactory-pro:7.19.4'
   - '-f'
   - 'jfrog-artifactory/Dockerfile.nginx'
   - '.' 
   
 - name: 'gcr.io/cloud-builders/docker'
   id: Build_xray-analysis_image
   args:
   - 'build'
   - '-t'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory/xray-analysis:3.25.1'
   - '-f'
   - 'jfrog-xray/Dockerfile.xray-analysis'
   - '.' 

