substitutions:
  _RT_VERSION: 7.19.4
  _XRAY_VERSION: 3.25.1
steps:
 - name: 'gcr.io/cloud-builders/docker'
   id: Build Deployer Image
   args:
   - 'build'
   - '-t'
   - 'gcr.io/$PROJECT_ID/jfrog-artifactory/deployer:7.19'
   - '.'
 - name: gcr.io/cloud-builders/docker
   id: Push Deployer Image
   args:
     - 'push'
     - 'gcr.io/$PROJECT_ID/jfrog-artifactory/deployer:7.19'
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args: 
     - "-c"
     - |
         #gcloud config set project jfrog-partnership-team
         #gcloud config set compute/zone asia-southeast1-a
         #gcloud config list
         #gcloud container clusters create anup-cluster --machine-type=f1-micro --preemptible --zone=asia-southeast1-a
         #kubectl get nodes
         ls 
 - name: 'gcr.io/cloud-builders/docker'
   id: Build Artifactory Image
   args:
   - 'build'
   - '--build-arg'
   - 'TAG=${_RT_VERSION}'
   - '-t'
   - 'gcr.io/$PROJECT_ID/jfrog-artifactory:${_RT_VERSION}'
   - '-f'
   - 'jfrog-artifactory/Dockerfile.artifactory'
   - '.' 
 - name: gcr.io/cloud-builders/docker
   id: Push Artifactory Image
   args:
     - 'push'
     - 'gcr.io/$PROJECT_ID/jfrog-artifactory:${_RT_VERSION}'
 - name: 'gcr.io/cloud-builders/docker'
   id: Build Artifactory-Nginx Image
   args:
   - 'build'
   - '--build-arg'
   - 'TAG=${_RT_VERSION}'
   - '-t'
   - 'gcr.io/$PROJECT_ID/jfrog-artifactory/nginx-artifactory-pro:$_RT_VERSION'
   - '-f'
   - 'jfrog-artifactory/Dockerfile.nginx'
   - '.' 
 - name: gcr.io/cloud-builders/docker
   id: Push Artifactory-Nginx Image
   args:
     - 'push'
     - 'gcr.io/$PROJECT_ID/jfrog-artifactory/nginx-artifactory-pro:$_RT_VERSION'
 - name: 'gcr.io/cloud-builders/docker'
   id: Build Xray-Analysis Image
   args:
   - 'build'
   - '-t'
   - 'gcr.io/$PROJECT_ID/jfrog-artifactory/xray-analysis:$_XRAY_VERSION'
   - '-f'
   - 'jfrog-xray/Dockerfile.xray-analysis'
   - '.' 
 - name: gcr.io/cloud-builders/docker
   id: Push Xray-Analysis Image
   args:
     - 'push'
     - 'gcr.io/$PROJECT_ID/jfrog-artifactory/xray-analysis:$_XRAY_VERSION'
 - name: gcr.io/cloud-builders/kubectl
   id: Configure kubectl
   args:
     - cluster-info
   env:
     - CLOUDSDK_COMPUTE_REGION=us-central1-b
     - CLOUDSDK_CONTAINER_CLUSTER=anup-cloudbuild
     - KUBECONFIG=/workspace/.kube/config
# - name: gcr.io/$PROJECT_ID/helm
#   id: update chart
#   args:
#     - ./chart/unified-mp
#     - dependency
#     - build
#  env:
#     - KUBECONFIG=/workspace/.kube/config
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args: 
     - "-c"
     - |
         ls chart/unified-mp/charts
         ./scripts/mpdev install --deployer=gcr.io/$PROJECT_ID/jfrog-artifactory/deployer:19 --parameters='{ "name": "$name", "namespace": "default", "xray.enabled": true, "artifactory-ha.nginx.tlsSecretName": "unified-tls-ingress", "artifactory-ha.nginx.service.ssloffload": true, "artifactory-ha.artifactory.node.replicaCount": 1, "artifactory-ha.artifactory.license.secret": "artifactory-license", "artifactory-ha.artifactory.license.dataKey": "artifactory.cluster.license", "artifactory-ha.database.type": "postgresql", "artifactory-ha.database.driver": "org.postgresql.Driver", "artifactory-ha.database.url": "${artifactory-ha.database.url}", "artifactory-ha.database.user": "artifactory", "artifactory-ha.database.password": "password", "xray.database.user": "artifactory", "xray.database.password": "password", "xray.database.url": "${artifactory-ha.database.url}", "xray.xray.jfrogUrl": "http://unified-nginx", "xray.xray.joinKey": "3d574bfedf8e7601de7bd22ee211d18e2e0cb38ce596fb4f90a770912edc9d52", "artifactory-ha.artifactory.joinKey": "3d574bfedf8e7601de7bd22ee211d18e2e0cb38ce596fb4f90a770912edc9d52" }'
   env:
     - name=unified
     - namespace=default
     - xray.enabled=true
     - artifactory-ha.nginx.tlsSecretName=unified-tls-ingress
     - artifactory-ha.nginx.service.ssloffload=true
     - artifactory-ha.artifactory.node.replicaCount=1
     - artifactory-ha.artifactory.license.secret=artifactory-license
     - artifactory-ha.artifactory.license.dataKey=artifactory.cluster.license
     - artifactory-ha.database.type=postgresql
     - artifactory-ha.database.driver=org.postgresql.Driver
     - artifactory-ha.database.url=jdbc:postgresql://postgres-postgresql:5432/artifactory
     - artifactory-ha.database.user=artifactory
     - artifactory-ha.database.password=password
     - xray.database.user=artifactory
     - xray.database.password=password
# - name: gcr.io/$PROJECT_ID/helm
#   id: Deploy chart
#   args:
#     - install
#     - postgres
#     - bitnami/postgresql
#     - --set
#     - persistence.size=20Gi
#   env:
#     - KUBECONFIG=/workspace/.kube/config
