steps:
 - name: 'gcr.io/cloud-builders/docker'
   id: Build-Deployer
   args:
   - 'build'
   - '-t'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory/deployer:7.18'
   - '.' 
 - name: 'gcr.io/cloud-builders/docker'
   id: Push-Deployer
   args:
   - 'push'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory/deployer:7.18'
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args: 
     - "-c"
     - |
         cd jfrog-artifactory
         ls 
 - name: 'gcr.io/cloud-builders/docker'
   id: BuildRT
   args:
   - 'build'
   - '-t'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory:7.18'
   - '-f'
   - 'jfrog-artifactory/Dockerfile.artifactory'
   - '.' 
 - name: 'gcr.io/cloud-builders/docker'
   id: Push-Artifactory
   args:
   - 'push'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory:7.18'
 - name: 'gcr.io/cloud-builders/docker'
   id: BuildNG
   args:
   - 'build'
   - '-t'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory/nginx-artifactory-pro:7.18'
   - '-f'
   - 'jfrog-artifactory/Dockerfile.nginx'
   - '.' 
 - name: 'gcr.io/cloud-builders/docker'
   id: Push-Artifactory-Nginx
   args:
   - 'push'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory/nginx-artifactory-pro:7.18'
