steps:
 - name: 'gcr.io/cloud-builders/docker'
   id: Build
   args:
   - 'build'
   - '-t'
   - 'gcr.io/jfrog-partnership-team/jfrog-artifactory/deployer:7.18'
   - '.' 
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args: 
     - "-c"
     - |
         ls -a
