FROM docker.bintray.io/jfrog/artifactory-pro:7.18.6

USER root
RUN mkdir -p /var/opt/jfrog/artifactory/etc/artifactory/info/
ADD jfrog-artifactory/info /var/opt/jfrog/artifactory/etc/artifactory/info/
RUN chown -R artifactory:artifactory /var/opt/jfrog/artifactory/etc/artifactory/

ADD jfrog-artifactory/sources /third-party-oss/sources/
ADD jfrog-artifactory/THIRD-PARTY-LICENSES /third-party-oss/
ADD jfrog-artifactory/Dockerfile.artifactory /docker/artifactory-pro/Dockerfile.GKE

USER artifactory
