FROM docker.bintray.io/jfrog/nginx-artifactory-pro:7.4.1

ADD jfrog-artifactory/sources /third-party-oss/sources/
ADD jfrog-artifactory/THIRD-PARTY-LICENSES /third-party-oss/
ADD jfrog-artifactory/Dockerfile.nginx /docker/artifactory-pro/Dockerfile.GKE
