ARG TAG

FROM releases-docker.jfrog.io/jfrog/router:7.18.2
ADD jfrog-xray/THIRD-PARTY-LICENSES /third-party-oss/
ADD jfrog-xray/Dockerfile.xray-router /docker/xray/Dockerfile.GKE
COPY jfrog-xray/xray.default /opt/jfrog/xray/app/bin
