ARG TAG

FROM releases-docker.jfrog.io/jfrog/xray-server:3.25.1
ADD jfrog-xray/THIRD-PARTY-LICENSES /third-party-oss/
ADD jfrog-xray/Dockerfile.xray-server /docker/xray/Dockerfile.GKE
COPY jfrog-xray/xray.default /opt/jfrog/xray/app/bin

