ARG TAG

FROM releases-docker.jfrog.io/jfrog/xray-analysis:3.25.1
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.xray-analysis /docker/xray/Dockerfile.GKE
COPY xray.default /opt/jfrog/xray/app/bin

#FROM releases-docker.jfrog.io/jfrog/xray-analysis:${TAG}
#ADD jfrog-xray/THIRD-PARTY-LICENSES /third-party-oss/
#ADD jfrog-xray/Dockerfile.xray-analysis /docker/xray/Dockerfile.GKE
#COPY jfrog-xray/xray.default /opt/jfrog/xray/app/bin
