ARG TAG

FROM releases-docker.jfrog.io/jfrog/xray-analysis:${TAG}
ADD jfrog-xray/THIRD-PARTY-LICENSES /third-party-oss/
ADD jfrog-xray/Dockerfile.xray-analysis /docker/xray/Dockerfile.GKE
COPY jfrog-xray/xray.default /opt/jfrog/xray/app/bin
